name: GitHub-Action-Example

on: push

jobs:
  my-fisrt-job:
    name: Meu Primeiro Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Rodando meu script
        run: |
          export VAR1=Hello
          
      - name: Rodando meu script
        run: |
          echo "VAR1=$VAR1"
          echo Vish...
          echo funciona! :-D 
  
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    needs: my-fisrt-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
