name: GitHub-Action-Example

on: push

jobs:
  my-fisrt-job:
    name: Meu Primeiro Job
    runs-on: ubuntu-latest
    
    outputs:
      info1: ${{ steps.step1.outputs.my_var }}
    
    env:
      MY_VAR: Eita
    
    steps:
      - name: Rodando meu script
        run: |
          echo "Olá mundo!"
          
      - name: Rodando meu script
        run: |
          echo "$MY_VAR ... funciona!"
          echo ":-D"

      - name: Teste para compartilhar info entre Jobs
        id: my_id
        run: echo "::set-output name=my_var::hahahaha Funciona mesmo!"

          
  my-second-job:
    name: Meu Segundo Job
    runs-on: ubuntu-latest
    needs: my-fisrt-job
   
    steps:
      - name: Rodando outro script novamente
        run: echo "${{ needs.my-fisrt-job.outputs.info1 }}"
          
      - name: Rodando outro script de novo novamente mais uma vez :-p
        run: |
          echo "\o/ Yeah!"
  
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    needs: my-second-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
